example/cypress/integration/c.spec.js, packages/api/package.json, packages/api/src/datasources/runs.ts, packages/api/src/lib/mongo.ts, packages/api/src/resolvers/index.ts, packages/api/src/schema.ts, packages/dashboard/src/components/run/details.tsx, packages/dashboard/src/components/run/summary.tsx, packages/dashboard/src/components/spec/summary.tsx, packages/dashboard/src/components/test/Test.tsx, packages/dashboard/src/components/test/TestDetails.tsx, packages/dashboard/src/components/test/index.tsx, packages/dashboard/src/lib/run.ts, packages/dashboard/src/views/InstanceDetailsView.tsx, packages/dashboard/src/views/RunDetailsView.tsx, packages/dashboard/src/views/RunsView.tsx, packages/director/src/app.ts, packages/director/src/config.ts, packages/director/src/execution/in-memory.ts, packages/director/src/execution/mongo/driver.ts, packages/director/src/execution/mongo/instances/instance.controller.ts, packages/director/src/execution/mongo/instances/instance.model.ts, packages/director/src/execution/mongo/runs/run.controller.ts, packages/director/src/execution/mongo/runs/run.model.ts, packages/director/src/lib/errors.ts, packages/director/src/types/driver.types.ts, packages/director/src/types/instance.types.ts, packages/director/src/types/run.types.ts, yarn.lock
- add `createdAt` to `Run`
- save screenshots URL to instance (for mongodb)
- show screenshots for failed tests in dashboard
- show run and instance details in dashboard
- show newest runs first, allow loading more (pagination)
=> Add various dashboard features

README.md
=> Updating the Demo & Example link

README.md, packages/api/src/generated/graphql.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/Root.tsx, packages/dashboard/src/components/commit/commit.tsx, packages/dashboard/src/components/layout/header.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/index.ejs, packages/dashboard/src/views/RunsView.tsx
=> Prevent failures for optional commit data on runs

README.md, packages/director/src/app.ts, packages/director/src/config.ts
=> Add support for ALLOWED_KEYS variable

packages/api/src/generated/graphql.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/components/common/index.tsx, packages/dashboard/src/components/instance/details.tsx, packages/dashboard/src/components/test/Test.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/lib/spec.ts, scripts/release-dockerhub.sh
=> Handle corrupted tests

README.md
=> Fixed Typos in ReadMe

README.md, packages/director/src/screenshots/s3/config.ts, packages/director/src/screenshots/s3/s3.ts
=> Add S3 ACL and S3_READ_URL_PREFIX customization

packages/dashboard/src/components/test/TestDetails.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/views/TestDetailsView.tsx, packages/dashboard/src/views/getInstance.graphql
=> Show error stack, if exists

README.md, bin/sorry-cypress.js, package.json, packages/api/src/generated/graphql.ts, yarn.lock
Regarding #8, this adds a helper script for rerouting cypress via your hosts file.
=> Add cypress wrapper

packages/director/.babelrc
=> Avoid using corejs builtins

packages/dashboard/src/views/RunsView.tsx
=> Disable polling to RunsView

.github/ISSUE_TEMPLATE/feature-request.md
Feature request issue template for our users. Figured we see how this works then we can make one for reporting bugs too.
=> Feature request issue template

kubernetes-full.yml
I appreciate that it's not a huge amount of work, but I deployed Sorry Cypress into Kubernetes and I thought this might help others in the future.
=> Add kubernetes example deployment

.github/workflows/dockerimage.yml, package.json, scripts/generateSemverTags.js, scripts/isSemver.js, scripts/release-dockerhub.sh
Handle pre-release tags for release dockerhub GH action scripts
=> Fix release script

.eslintrc.js, packages/dashboard/package.json, packages/dashboard/src/components/common/date.tsx, packages/dashboard/src/components/run/summary.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/hooks/useAsync.ts, packages/dashboard/src/lib/apolloClient.ts, packages/dashboard/src/lib/navigation.ts, packages/dashboard/src/lib/run.ts, yarn.lock
=> Use local time

README.md
You've created a beautiful project and we're looking to employ your solution as our daily driver soon.
Thank you for all the effort you've put into this.
This PR is meant to clarify the legal situation surrounding the licensing of cypress.
While sorry-cypress may not be legal for open source projects per se, the MIT License is what allows this.
Have a beautiful day
=> Clarify legal situation

packages/dashboard/src/components/common/date.tsx, packages/dashboard/src/components/run/summary.tsx
=> Fix Date import

packages/api/src/generated/graphql.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/components/layout/header.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/views/ProjectsView.tsx
=> Add "new project" button to welcome screen

packages/api/src/generated/graphql.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/components/common/index.tsx, packages/dashboard/src/components/run/RunList.tsx, packages/dashboard/src/components/run/summary.tsx, packages/dashboard/src/components/ui/FlexRow.tsx, packages/dashboard/src/components/ui/PageControls.tsx, packages/dashboard/src/components/ui/SearchField.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/views/ProjectsView.tsx, packages/dashboard/src/views/RunsView.tsx
This PR implements runs filtering by ci build id as well as some minor code and style refactoring.
Closes #59
=> Add run filtering by ci build id

packages/director/src/lib/hooksReporter.ts
you need to check that there are headers, and then try to parse them.
it is error
=> Fix bug if header don't set. #193

cloudfront/sorry-cypress.yml
Add `S3_REGION` env to cloud formation tempalte.
Fixes #195
=> #195 Add S3_REGION env to cloudformation

packages/director/src/api/runs.ts, packages/director/src/execution/in-memory.ts, packages/director/src/execution/mongo/projects/project.model.ts, packages/director/src/execution/mongo/runs/run.controller.ts, packages/director/src/types/run.types.ts
=> Prevent falsely emited "run started" hooks

docker-compose.cos.yml, docker-compose.full.yml, docker-compose.minio.yml
Please see the issue description here:
https://github.com/sorry-cypress/sorry-cypress/issues/238
=> fix(#238): add persistent storage for mongo in docker-compose configs

packages/director/src/execution/in-memory.ts, packages/director/src/lib/hooks/reporters/controller.ts
=> fix: prevent hooks for inmemory driver

packages/common/package.json, packages/common/src/run/types.ts, packages/director/src/api/runs.ts, packages/director/src/execution/in-memory.ts, packages/director/src/execution/mongo/runs/run.controller.ts, packages/director/src/lib/ciBuildId.ts, packages/director/src/lib/hash.ts
=> feat: support ciBuildId from major CI providers

packages/dashboard/nginx/default.conf.template
=> fix: add explicit mime type for mjs

packages/dashboard/src/root.tsx
Thanks a lot for the PR 👍🏻
Your contribution is very valuable, we **really appreciate your time and effort**!
For bug fixes:
---
--- Side note ---
Time is very valuable resource and we are trying to use it wisely - your time and our time. The reality of maintaining on open-source software is:
- Adding a new code and / or feature complicates the maintenance
- Most people disappear after contributing a feature, leaving the support to core maintainers
Given that, please don't be offended if your PR is rejected or significantly modified.
P.S.
Here's an interesting discussion about OSS contributions https://changelog.com/podcast/433
❤️
=> Fix support to projects with slashes

packages/api/src/generated/graphql.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/components/common/executionState.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/instance/details.tsx, packages/dashboard/src/instance/getInstance.graphql, packages/dashboard/src/instance/summary.tsx, packages/dashboard/src/run/runDetails/details.tsx, packages/dashboard/src/run/runDetails/runDetailSpec.fragment.graphql
=> fix: handle nullable results.tests

packages/dashboard/src/components/common/testResults.tsx, packages/dashboard/src/run/runDetails/details.tsx
=> fix: show correct duration in specs list

packages/dashboard/src/project/hook/editBranchFilter.tsx, packages/director/src/lib/hooks/reporters/__tests__/slack.test.ts, packages/director/src/lib/hooks/reporters/slack.ts
=> feat: let excluding branches to trigger slack hooks

packages/dashboard/src/lib/github.ts, packages/dashboard/src/run/commit/commit.tsx
Bug fixe:
- closes #392
- please check issue description to see how to test it
Note: tested locally, no idea how release process works and if I should do anything about it.
=> Handle SSH URLs

packages/dashboard/src/project/projectEditView.tsx
For bug fixes:
https://user-images.githubusercontent.com/5295554/140765428-59dede9c-30ef-4aa3-a827-764692d73ca4.mp4
=> fix(project): refetch projects after create, update, delete a project

packages/dashboard/src/components/layout/sidebar.tsx
For bug fixes:
Fixes #228.
---
--- Side note ---
Your contribution is very valuable, we **really appreciate your time and effort**!
Please note:
- Adding a new code and / or feature complicates the maintenance
- Most people disappear after contributing a feature, leaving the support to core maintainers
Given that, please don't be offended if your PR is rejected or significantly modified.
=> Fix sidebar details menu links when projectId has slashes

packages/dashboard/package.json, packages/dashboard/src/run/runDetails/runDetails.tsx, yarn.lock
=> feat: make grid coulmns sortable and filterable

packages/dashboard/src/components/ui/toolbar.tsx, packages/dashboard/src/hooks/useReadableSpecNames.ts, packages/dashboard/src/lib/path.ts, packages/dashboard/src/run/runDetails/runDetails.tsx, packages/dashboard/src/run/runDetails/runDetailsView.tsx
=> feat: allow toggling readable spec names

packages/dashboard/src/components/ui/searchField.tsx
closes #620
For bug fixes:
---
--- Side note ---
Your contribution is very valuable, we **really appreciate your time and effort**!
Please note:
- Adding a new code and / or feature complicates the maintenance
- Most people disappear after contributing a feature, leaving the support to core maintainers
Given that, please don't be offended if your PR is rejected or significantly modified.
=> feat(dashboard): add search value in the URL (deeplink)

packages/dashboard/src/ciBuild/ciBuildSummary.tsx
=> fix: add project summary for single project

packages/api/Dockerfile, packages/director/Dockerfile
For bug fixes:
- [x ] Add a reference to the original issue - #645
- [x ] Add a test and / or some kind of instructions to verify the fix  - none needed
=> feat: make USER an ARG so containers based on this one can switch between root and $USER

docker-compose.azure-blob-storage.yml, docker-compose.build.yml, docker-compose.cos.yml, docker-compose.full.yml, docker-compose.minio.yml, packages/api/Dockerfile, packages/dashboard/Dockerfile, packages/director/Dockerfile
=> Update nodejs to lts

packages/dashboard/src/components/ui/player.tsx, packages/dashboard/src/instance/instanceDetails.tsx
For bug fixes:
---
About this feature:
Clicking on a specific test duration from the list on the spec run instance page will rewind the recording to the start of that test.
=> Add ability to seek recording video on click

docker-compose.minio.yml
Added username and password to secure mongodb
Fixed minio server run command and exposed needed ports
Added comments explaining required changes before deploying
=> fix: update docker-compose.minio.yml file

packages/api/src/config.ts, packages/api/src/index.ts, packages/dashboard/server/app.js, packages/dashboard/server/config.js, packages/director/src/app.ts, packages/director/src/config.ts
For bug fixes:
---
This adds an environment variable for base path override, for reverse proxy purposes
=> Add base path overrides

packages/api/Dockerfile, packages/dashboard/Dockerfile, packages/director/Dockerfile, scripts/release-dockerhub.sh
Reverts sorry-cypress/sorry-cypress#735
=> Revert "Multi Architecture Docker Images"

scripts/release-dockerhub.sh
Reverts sorry-cypress/sorry-cypress#742
=> Revert "Fix Multi Arch Build"

.husky/pre-commit, package.json, yarn.lock
=> fix: patch security warnings, upgrade husky

packages/dashboard/src/instance/instanceDetails.tsx
=> fix: prevent crash when attempts are missing

packages/director/src/screenshots/s3/config.ts
=> fix: properly resolve UPLOAD_EXPIRY_SECONDS value

.github/workflows/dockerimage-api.yml, .github/workflows/dockerimage-dashboard.yml, .github/workflows/dockerimage-director.yml, packages/api/Dockerfile, packages/dashboard/Dockerfile, packages/director/Dockerfile, scripts/release-dockerhub.sh
Addition of Arm64 Docker images, in order to be able to deploy it in Graviton based nodes.
-
Closes #734
=> Start building Arm64 Docker image

cloudformation/sorry-cypress.yml
=> fix: remove deprecated S3 ACL from CF [skip ci]

cloudformation/sorry-cypress-advanced-deployment.yml, cloudformation/sorry-cypress.yml, cloudformation/standard-networking.yml
- support local and remote DBs
- provide many more parameters for customization
- provide autoscaling feature
- security settings
- KMS key encryption
- more!
> Describe the use-case in details
Closes #809
=> Draft: Make CFT more robust

packages/director/src/lib/hooks/reporters/slack.ts
Reverts sorry-cypress/sorry-cypress#830
=> Revert "Update slack.ts for improved newline formatting"

packages/dashboard/src/project/projectListItem.tsx
=> Count all groups of a run for projects view

package.json, yarn.lock
#851
> Describe the use-case in details
=> build(deps): change pac-resolver to 7.0.0
