packages/director/src/screenshots/s3/config.ts
The fix for #48  has an issue in reading the S3_ACL environment variable. This PR fixes that.
=> Fix reading of S3 ACL environment variable

packages/api/src/datasources/runs.ts
The query `runs` returns an error stating `Expected Iterable, but did not find one for field Query.runs.`  as the object returned from the resolver does not match the Query schema. So I fixed the getAllRuns api to use the `fullRunReducer` instead of the `runFeedReducer`
fixes #62
=> Fix runs query resolver to match schema

packages/director/src/screenshots/s3/config.ts, packages/director/src/screenshots/s3/s3.ts
Add the following config options to s3 driver to add custom upload key prefixes, this should help segregate images and videos.
- S3_IMAGE_KEY_PREFIX
- S3_VIDEO_KEY_PREFIX
Also please update the s3 wiki with the following: 
**`S3_IMAGE_KEY_PREFIX`**
The prefix to use when uploading the screenshots.
Setting S3_IMAGE_KEY_PREFIX to `images` will change the generated S3 object key for screenshots to `images/${key}`.
`S3_IMAGE_KEY_PREFIX=<null>`
**`S3_VIDEO_KEY_PREFIX`**
The prefix to use when uploading the videos.
Setting S3_VIDEO_KEY_PREFIX to `videos` will change the generated S3 object key for videos to `videos/${key}`.
`S3_VIDEO_KEY_PREFIX=<null>`
=> Add support for custom key prefixes for s3 uploads

packages/dashboard/src/components/layout/header.tsx, packages/dashboard/src/hooks/useAutoRefresh.ts, packages/dashboard/src/hooks/useLocalStorage.ts, packages/dashboard/src/views/InstanceDetailsView.tsx, packages/dashboard/src/views/RunDetailsView.tsx, packages/dashboard/src/views/TestDetailsView.tsx
I did not do anything with the auto refresh on the runs page. Due to the stuff with load more. If we switch that to pagination hopefully that will be simple to implement.
Also on a side note for global state are we planning to just use apollo cache? If so maybe I can migrate the local storage updating and such to somewhere in the application bootstrap.
=> Adding auto reload toggle and tooltips on breadcrumbs

.eslintrc.js, package.json, packages/api/src/datasources/runs.ts, packages/api/src/generated/graphql.ts, packages/api/src/resolvers/index.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/components/run/details.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/views/RunDetailsView.tsx, packages/dashboard/src/views/getRunsByProjectIdLimitedToTiming.graphql, packages/director/src/screenshots/minio/minio.ts
The idea here is to give you an estimate of how long each spec is going to take to run. This could also be used to add heuristics to a run. But that is way more ambiguous. Since you could make an estimate on how long all the specs will run in tandem. Or based on having 5 test runners. Or based on all in parallel. This needs more thought. I think I good guess most of the time would be getting the earliest spec start time and latest spec end time for the last 5 runs and averaging that time gap but 🤷  it does not cover everycase.
=> Add heuristics to run view.

packages/api/src/datasources/projects.ts, packages/api/src/generated/graphql.ts, packages/api/src/resolvers/index.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/Root.tsx, packages/dashboard/src/components/project/projectListItem.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/views/InstanceDetailsView.tsx, packages/dashboard/src/views/ProjectEditView.tsx, packages/dashboard/src/views/ProjectsView.tsx, packages/dashboard/src/views/RunsView.tsx, packages/dashboard/src/views/TestDetailsView.tsx, packages/dashboard/src/views/createProject.graphql, packages/dashboard/src/views/deleteProject.graphql, packages/dashboard/src/views/getProject.graphql, packages/dashboard/src/views/updateProject.graphql
I intentionally did not handle pagination. I think we need a project wide solution. Although it will only probably be used by projects and runs right now. 🤷  @agoldis let me know what you wanna do with pagination.
So net new stuff is.
Project list page is actually not garbage. (I can say this cause I made it originally.) Its just missing pagination.
Projects can be added.
Projects can be deleted. (and cleaned up including runs and instances) It would be nice to have it clean up S3 aswell
Projects can be updated. (disabled in the UI until there is more project data to update)
Project list page UI has a new look.
Project edit page has been added.
=> Adding the UI to list and create / update projects.

packages/dashboard/src/components/test/TestDetails/TextDetailsV5.tsx
`useSwitch` accepts an initialising argument which defaults to `false`. [Source](https://github.com/sorry-cypress/sorry-cypress/blob/69f1eadd344cd2f5aa86c7d8634714401e6ad339/packages/dashboard/src/hooks/useSwitch.ts#L11).
To be able to display the screenshots on the Test Details we need to provide `true`.
Fixes #154.
=> Fix: screenshots are not shown in TestDetailsV5

packages/dashboard/src/components/run/details.tsx, packages/dashboard/src/hooks/useHideSuccessfulSpecs.ts, packages/dashboard/src/hooks/useLocalStorage.ts
The `Hide successful specs` switch is now persisted in local storage (single value for all projects/runs)
I also added export of the `SetLocalStorageValue` TypeScript interface, because it is the return type for `useAutoRefresh` and `useHideSuccessfulSpecs` and therefore can not be private.
Closes #139
=> Persist "Hide passing tests" in local storage

CONTRIBUTE.md, docker-compose.dev.yml, docker-compose.full.yml, docker-compose.minio.yml, docker-compose.yml
Closes #190 
This PR addresses exposure of unneeded ports in docker-compose files. These files are very convenient to use but might provide a high risk when used for running on an actual server/cloud. Because the [documentation](https://sorry-cypress.dev/quickstart) only mentions running the `docker-compose.minio.yml`, I would like to make the intend more clear by adding a `docker-compose.dev.yml` that can be used on top of other docker compose files to expose extra ports.
I feel like these changes could be documented somewhere but on the other hand anyone who works on the project and needs the extra ports locally will figure it out, since this was not documented before either.
- `docker-compose.yml`
- removed node debug port `9230` from `api` service
- removed node debug port `9229` from …
=> Remove unneeded port exposure in docker-compose files

docker-compose.build.yml, packages/api/.dockerignore, packages/api/Dockerfile, packages/api/package-lock.json, packages/api/package.json, packages/dashboard/.dockerignore, packages/dashboard/Dockerfile, packages/dashboard/nginx.conf, packages/dashboard/package-lock.json, packages/director/.dockerignore, packages/director/Dockerfile, packages/director/package-lock.json
I tried to further slim down api and director images using webpack, but failed to create a reliable build.
Nevertheless image sizes for api and director is about halved by locking dependency versions and excluding dev dependencies from the images using multistage builds. Image size for dashboard is less than a 10th of the original by only including the statically compiled browser client into a vanilla nginx image. 
Memory consumption during runtime for dashboard was reduced to almost nothing, due to nginx' resource consumption being barely noticable.
=> Reduce dashboard memory usage

docker-compose.build.yml, docker-compose.cos.yml, docker-compose.full.yml, docker-compose.minio.yml, kubernetes-cos.yml, kubernetes-full.yml, packages/dashboard/Dockerfile, packages/dashboard/nginx.conf, packages/dashboard/nginx/default.conf.template, packages/dashboard/src/state/environment.ts
Allows dynamic port binding for dashboard via `PORT` env var. Hardcoded `8080` would not allow running on heroku, and, in general, should not be hardcoded. 
It is a follow up on @slinstaedt work in #230, which was awesome because it reduced image size significantly (and caused me to explore multi-staged Dockerfiles).
@tico24
One less-desired side effect is that dashboard environment variables are now mandatory to run production. I have updated kubernetes templates accordingly. I guess we also need to update helm charts?
=> Allow dynamic port binding for dashboard

docker-compose.build.yml, docker-compose.cos.yml, docker-compose.full.yml, docker-compose.minio.yml, packages/dashboard/Dockerfile, packages/dashboard/nginx/default.conf.template, packages/dashboard/server/app.js, packages/dashboard/server/config.js, packages/dashboard/src/config.ts, packages/dashboard/src/lib/apolloClient.ts, packages/dashboard/src/state/environment.ts
This PR adds a `GRAPHQL_CLIENT_CREDENTIALS` to allow configuring [GraphQL's authentication](https://www.apollographql.com/docs/react/networking/authentication/#cookie) when the apollo client (`GRAPHQL_SCHEMA_URL`) is external.
**Note: if the environment variables are not set, there aren't any behavior changes.**
=> Add support to ApolloClient credentials in the dashboard

packages/api/src/generated/graphql.ts, packages/api/src/schema/schema.graphql, packages/common/src/hook/types.ts, packages/common/src/run/types.ts, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/project/getProject.graphql, packages/dashboard/src/project/hook/createSlackHook.graphql, packages/dashboard/src/project/hook/editBranchFilter.tsx, packages/dashboard/src/project/hook/editHookEvents.tsx, packages/dashboard/src/project/hook/hook.utils.ts, packages/dashboard/src/project/hook/hookEdit.tsx, packages/dashboard/src/project/hook/slackHook.tsx, packages/dashboard/src/project/hook/validation.ts, packages/dashboard/src/project/hooksEditor.tsx, packages/director/src/lib/hooks/__tests__/fixtures/slackHook.json, packages/director/src/lib/hooks/__tests__/fixtures/slackReportStatusRequest.json, packages/director/src/lib/hooks/__tests__/hooksReporter.test.ts, packages/director/src/lib/hooks/__tests__/utils.test.ts, packages/director/src/lib/hooks/reporters/controller.ts, packages/director/src/lib/hooks/reporters/generic.ts, packages/director/src/lib/hooks/reporters/slack.ts, packages/director/src/lib/hooks/utils.ts
We have faced with 3 issues in a current slack flow:
1. We want to get notification about only failed builds, not all builds.
2. We have dozens of branches, we want to know only about failed builds from **develop**, **master** and **release-\*** branches.
3. We need more information in slack message (commit message), also need to fix confusion with skipped/pending (https://github.com/cypress-io/cypress/issues/3092)
So, I have added:
1. Result filter (ALL, ONLY_FAILED, ONLY_SUCCESSFUL). Required field, default value is ALL.  
2. Branch filter (with '*' and '?' wildcards support). Optional field, empty state means filter is off, all branches are tracked. 
3. New Slack message layout.
Edit hook before:
Edit hook after:
Slack message before:
Slack message after:
Passed:
Failed:
=> Add slack hook filters and advanced formatting

packages/api/src/datasources/runs.ts, packages/director/src/execution/mongo/runs/run.model.ts
$map is incompatible with the current version of Amazon DocumentDB, removing it allows sorry-cypress to be more easily deployed in AWS using the mongo "api-compatible" DocumentDB.
I have not used mongo heavily before, but from my testing this seems to give the same result.
Would potentially fix https://github.com/sorry-cypress/sorry-cypress/issues/133
=> Remove mongo $map usages to simpler syntax

packages/director/src/lib/hooks/__tests__/fixtures/bitbucketReportStatusRequest.json, packages/director/src/lib/hooks/reporters/bitbucket.ts
Currently the commit sha is used as the key in the request to add/update the BitBucket status. The key is the externally generated unique reference used to identify the status via the BitBucket API.
Using the commit sha means that if you have a monorepo with multiple Sorry Cypress projects setup, the latest hook will override the status. For example, we have 4 projects in the same monorepo which all have BitBucket hooks setup. I have named them uniquely but because they all use the commit sha to add/update the status, they override each other. This is frustrating because it means you do not get a status for each of the projects, so if one fails it's failed status won't be shown if the latest one passes. 
This change uses the hookId (a UUID) as the key instead. This ensures the keys will …
=> feature: support monorepos for BitBucket hooks

packages/director/src/lib/hooks/__tests__/fixtures/slackReportStatusRequestWithoutCommitData.json, packages/director/src/lib/hooks/__tests__/hooksReporter.test.ts, packages/director/src/lib/hooks/reporters/slack.ts
Commit data is not always present on a run. Slack hooks should still fire when commit branch and message are not set.
Was struggling to find where the run commit data (i.e. sha, branch and message) are currently captured from, but in our case they are never defined. This change ensures the slack hooks still fire when these are missing.
Thanks a lot for the PR 👍🏻
Your contribution is very valuable, we **really appreciate your time and effort**!
For bug fixes:
---
--- Side note ---
Time is very valuable resource and we are trying to use it wisely - your time and our time. The reality of maintaining on open-source software is:
- Adding a new code and / or feature complicates the maintenance
- Most people disappear after contributing a feature, leaving the support to core …
=> Successfully fire slack hooks without commit data

packages/director/src/lib/ciBuildId.ts
CI_BUILD_ID is no longer set by Gitlab CI, per fsharp/FAKE#2290.
Not referencing an issue as there is none filed, but I can file/reference if needed.
I have confirmed CI_PIPELINE_ID is a viable env var by running Cypress with explicit `--ci-build-id $CI_PIPELINE_ID` (which works) and `--ci-build-id $CI_BUILD_ID` (which does not).
=> fix: correctly extract ciBuildId from Gitlab CI

.gitignore, packages/api/src/datasources/instances.ts, packages/api/src/generated/graphql.ts, packages/api/src/resolvers/index.ts, packages/api/src/schema/schema.graphql, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/run/runDetails/details.tsx, packages/dashboard/src/run/runDetails/resetInstance/resetInstance.graphql, packages/dashboard/src/run/runDetails/resetInstance/resetInstanceButton.tsx, packages/mongo/src/config.ts
Basically, my tests sometimes fail due to flakiness, and I need some way to reset only a specific instance, instead of having to run the whole suite again.
This allows sorry cypress to run just the failed tests again by making it as if they haven't been picked up by any executor yet.
Happy to hear any comments you have.
=> feature: allow reset of instance to facilitate retesting

packages/dashboard/src/root.tsx, packages/dashboard/src/run/runsRedirect.tsx
Small PR to do a thing that we're now constantly doing manually. I haven't found a way to link directly to a project/build-id combination, so I've added one.
I'm not really proud of the implementation, but I couldn't find a better way of implementing the redirect logic using react router.
=> feat: allow linking directly to a project/build-id combination

packages/api/src/datasources/instances.ts, packages/api/src/datasources/runs.ts, packages/api/src/resolvers/index.ts, packages/mongo/src/db.ts
This PR changes the behavior of the deletion of runs in a specified date range.
Previously, it used a very slow `aggregate` to find the `instances` for the `runs` that should be deleted and tried to delete them all at once. This timeouted at various ends in larger setups.
With this change, it will now process the deletion in batches:
1. Get a batch of `runIds`
2. Delete all associated `instances` for those `runIds`
3. Delete the `runs` for those `runIds`
4. Repeat until no more `runs` are found for the defined date-range
5. 
To make it even faster, a new index for `runId` is added to the `instance` collection.
=> Delete runs in daterange in batches

packages/dashboard/src/components/layout/sidebar.tsx
=> fix: use grid to prevent items overflow

packages/api/src/datasources/instances.ts, packages/dashboard/src/run/runDetails/resetInstance/resetInstanceButton.tsx
=> fix(instance): update stats after user resets an instance

cloudformation/sorry-cypress.yml
Hi there, I updated the health checks in the CloudFormation stack as they were a bit cumbersome. 
- The Apollo webserver for GraphQL offers `/.well-known/apollo/server-health` as [health path](https://www.apollographql.com/docs/apollo-server/monitoring/health-checks/) -> you get HTTP 200 as return value which is way more intuitive matcher than 400 :) 
- I also updated the Director health check to `/ping` which allows the usage of HTTP 200 as matcher
I increased `HealthCheckIntervalSeconds` to 15 seconds. This is more than enough and you have less log entries with simple health check GET requests in AWS Cloudwatch. I deployed the improved health checks on my cluster today and they work fine.
=> updated the CloudFormation Stack with proper health checks

cloudformation/sorry-cypress.yml
Due to URL changes within Docker, docker.io needs to be removed for successful pulling Docker Images of Sorry-Cypress.
Use Case: AWS CloudFormation throws an error when pulling images from Docker as docker.io is not supported anymore.
=> Remove docker.io domain from Image pull in CloudFormation .yml

packages/dashboard/src/components/layout/sidebar.tsx, packages/dashboard/src/lib/navigation.ts, packages/dashboard/src/project/projectEditView.tsx, packages/dashboard/src/project/projectListItem.tsx
=> fix: encode project ids wherever it is used in url

packages/api/Dockerfile, packages/director/Dockerfile
Shrink nodejs containers by using multistage builds more effectively:
* api: 306MB > 147MB
* director: 445MB > 184MB
Use [tini](https://github.com/krallin/tini) to ensure that nodejs processes respond to things like `SIGINT`.
Use `node` user instead of `root` user
=> Dockerfile efficiencies

packages/api/src/config.ts, packages/api/src/index.ts
Hi everyone, I'm not a frequent contributor to OSS so please pardon the formatting.
This is a *very* basic add-on that probably should have already existed in the project. I couldn't find any open issues relating to it, but the use-case is very simple. There are folks such as myself that don't have the luxury of spinning up the CloudFormation template or standing up a bunch of dedicated infrastructure to run this application in its default configuration. This requires us to tweak the configuration to support our use-case. Unfortunately, sorry-cypress (the API package specifically) does not support specifying an alternative `HOST` i.e. `0.0.0.0`, which breaks things like docker configurations that rely on `bridge` networking modes. For our specific use-case, we didn't want to have to use …
=> Add HOST parameter to API config.

packages/director/src/execution/in-memory.ts, packages/director/src/execution/mongo/runs/run.controller.ts, packages/director/src/lib/hash.ts
For bug fixes:
Closes #541 
usually in PRs, we merge the branch with the master so we can have different `commit sha` in parallel runs. but the commit message is the same. so instead of `commit sha` is better to use `commit message` for runId.
_we are using bitbucket CI and in bitbucket CI we have this situation_
=> use commit message instead of sha

.github/workflows/dockerimage-api.yml, .github/workflows/dockerimage-dashboard.yml, .github/workflows/dockerimage-director.yml, .github/workflows/tests.yml
This is just to update the GH Actions rules with their updates, specially `login-action` with several updates including aws-sdk updates and e2e coverage
=> Updating GH actions to latest versions

packages/api/src/generated/graphql.ts, packages/dashboard/src/components/common/runState.tsx, packages/dashboard/src/components/common/specState.tsx, packages/dashboard/src/generated/graphql.ts, packages/dashboard/src/instance/instanceSummary.tsx, packages/dashboard/src/run/runDetails/runDetails.tsx, packages/dashboard/src/run/runSummary/runSummary.tsx, packages/dashboard/src/run/runSummaryTestResults/runSummaryTestResults.tsx, packages/director/src/api/instances.ts, packages/director/src/execution/mongo/instances/instance.controller.ts, packages/director/src/execution/mongo/runs/run.model.ts
This modifies the code in the director that receives statuses from cypress, and converts those statuses to something that makes sense in the sorry-cypress interface.
This is relation to the issues described in #555, but also my own issues trying to query the sorry cypress API and getting a whole bunch of pending tests back when my tests are already complete.
When directory receives the following statuses from cypress they're converted:
- `pending`: converted into `skipped`
- `skipped`: converted into `failed`, this should really remain 'skipped', but I can't make a distinction between error-skipped, and desired skipped
This will result in the interface never displaying any pending tests if the instance has completed.
It also adds display for total number of tests per instance/run/tests …
=> fix: fixes #555 mocha statuses are converted to cypress statuses

packages/api/package.json, packages/api/src/index.ts, packages/api/src/lib/express.ts, packages/director/src/app.ts, packages/director/src/execution/in-memory.ts, packages/director/src/execution/mongo/driver.ts, packages/director/src/types/driver.types.ts, packages/mongo/src/db.ts, yarn.lock
**New feature**
In certain case, the connexion to the MongoDB is lost and the director / GraphQL API must be rebooted in order for the connexion to work properly again.
This PR aims to implement a health check which allows to check if the connexion with the database is healthy. This health check makes it possible to automate the restart of the director / GraphQL API, through a Kubernetes liveness probe as an example.
A route `/health-check-db` is added on both the director and the GraphQL API. The health check use the ping command (https://www.mongodb.com/docs/manual/reference/command/ping/) provided by MongoDB.
The implementation is very simple for the director as we just add an another route on the express application.
For the GraphQL API in order to add a route, we need to use …
=> Add mongodb health checks

docker-compose.azure-blob-storage.yml, packages/director/package.json, packages/director/src/screenshots/azure-blob-storage.driver.ts, packages/director/src/screenshots/azure-blob-storage/azure-blob-storage.ts, packages/director/src/screenshots/azure-blob-storage/config.ts, packages/director/src/screenshots/azure-blob-storage/index.ts, yarn.lock
This PR aims to add support for Azure Blob Storage for screenshots / video uploads. Link to issue : https://github.com/sorry-cypress/sorry-cypress/issues/74
I implemented the support for Azure Blob Storage using the ScreenshotsDriver interface. It was very straight-forward.
I also added a `docker-compose.azure-blob-storage.yml` which allows to start a full environment with a Azure Blob Storage container, similar to what is done is `docker-compose.minio.yml` and `docker-compose.cos.yml`.
Also, I remarked that there is a lot of duplicated code in the files related to screenshots drivers. I think it would be a good idea to refactor that in an other PR. What do you think ?
In order to test this feature easily, I created another PR which add a route `generate-upload-urls-blob-storage` to the …
=> Add Azure Blob Storage support

packages/api/src/lib/query.ts, packages/dashboard/src/run/runsFeed/useGetCiBuildId.ts, packages/dashboard/src/run/runsRedirect.tsx, packages/mongo/src/db.ts, yarn.lock
These additions improve the speed of the `/[project]/runs` page when you have a large number of runs. Previous aggregation query was only using an index for sorting, but still had to page through all runs to filter the results.
I also replaced the `/[project]/runs/[ciBuildId]` query to take advantage of the new indexes (previous query was using a regular expression match for something that was guaranteed to be the full value).
=> feat: add indexes to speed up the runs page and ci build redirect query

packages/dashboard/src/components/layout/sidebar.tsx
This fixes #581.
It reduces project items' font size to 16px, reduces their left padding to 16px, and removes `white-space: no-wrap` from the sidebar, so large project names are displayed properly, both in the project title and in the sidebar item.
Previously, I thought of ellipsis with some kind of tooltip, but I see no problem with this implementation too. Anyway, I'm open to suggestions.
Additionally, there is no horizontal scroll on the sidebar anymore.
To test this, just add some very large project names, as in the following screenshots:
=> Enhance sidebar layout

packages/dashboard/src/components/layout/sidebar.tsx, packages/dashboard/src/project/projectListItem.tsx
Fixes an edge case of #608.
It forces `word-wrap: break-all` on sidebar items and dashboard project list item card, to avoid horizontal scroll on very large words. To test it, just add a project with a very long word, or even a long word right before the first row ends.
Note: if you wish I can add a polyfill, but IMHO is not necessary:
https://caniuse.com/?search=word-break
Before:
After:
=> Fix word break overflow

docker-compose.azure-blob-storage.yml, docker-compose.minio.yml
This PR improves the docker-compose.minio.yml by changing the networking in order to allows the signature to correctly work.
Before this PR, the upload url sent back by the director is `"https://storage:9000/..."`. The hostname storage is not resolved to anything outside of Docker, except if you modify your /etc/hosts, so you cannot use this url. Also, you cannot change the hostname to localhost because of the signature.
By changing the networking, the director can communicate with minio using the localhost hostname and sign urls using localhost hostname and send back `"https://localhost:9000/..."` as upload urls, which works !
Also this PR fix a circular dependency in `docker-compose.azure-blob-storage.yml` that prevented the docker-compose file to be run.
=> Fix upload urls in docker-compose.minio.yml

packages/director/src/execution/__tests__/in-memory.test.ts, packages/director/src/execution/in-memory.ts, packages/director/src/execution/mongo/runs/run.controller.ts
Fixes #625
[Successfull CI run](https://github.com/bjartur20/sorry-cypress/actions/runs/2868228819)
The director was saving the gitlab_ci_token with the remoteOrigin when running tests in GitlabCI.
This fix removes the gitlab_ci_token from the remoteOrigin parameter, ensuring that only the remoteOrigin is included in the URL.
Also wrote a test for this for in-memory execution.
Please let me know if this should be fixed in any other way :)
For bug fixes:
=> Fixed issue where director saves the gitlab_ci_token in remoteOrigin

cloudformation/sorry-cypress.yml, docker-compose.azure-blob-storage.yml, docker-compose.build.yml, docker-compose.cos.yml, docker-compose.full.yml, docker-compose.minio.yml, packages/api/src/config.ts, packages/api/src/index.ts
I don't see it as wise to enable Apollo Server's playground by default. Using `ApolloServerPluginLandingPageDisabled` we could parameterize the activation of the landing page.
```
const apolloServer = new ApolloServer({
typeDefs,
resolvers,
dataSources: () => dataSources,
introspection: true,
plugins: [
APOLLO_PLAYGROUND === 'false'
? ApolloServerPluginLandingPageDisabled()
: ApolloServerPluginLandingPageGraphQLPlayground(),
],
});
```
With APOLLO_PLAYGROUND set on `false`
```
api:
build:
dockerfile: packages/api/Dockerfile
context: .
image: agoldis/sorry-cypress-api:${VERSION:-latest}
environment:
MONGODB_URI: 'mongodb://mongo:27017'
MONGODB_DATABASE: 'sorry-cypress'
APOLLO_PLAYGROUND: 'false'
ports:
- 4000:4000
depends_on:
- mongo
```
With APOLLO_PLAYGROUND set on `true`
```
api:
build: …
```
=> feat(apollo): makes optional the enable of the landing page playground

package.json, packages/director/package.json, packages/director/src/execution/__tests__/in-memory.test.ts, packages/director/src/execution/__tests__/mongo.test.ts, packages/director/src/execution/mongo/runs/run.controller.ts
Related issue: #625 
[Successfull CI run](https://github.com/bjartur20/sorry-cypress/runs/7879964604)
I used the wrong index to access the url for remoteOrigin in the mongo driver. This PR fixes that issue and adds a test for it.
=> Fix wrong indx for remote origin

packages/director/src/execution/__tests__/in-memory.test.ts, packages/director/src/execution/__tests__/mongo.test.ts, packages/director/src/execution/in-memory.ts, packages/director/src/execution/mongo/runs/run.controller.ts, packages/director/src/execution/utils.ts
Related issue: #625
[Successfull CI run](https://github.com/bjartur20/sorry-cypress/actions/runs/2882079533)
- Better parsing of the remoteOrigin for a run using URL().
- Fixed typo in enhaceSpecForThisRun.
=> now uses URL to parse remoteOrigin

.github/workflows/tests.yml, packages/api/tsconfig.json, packages/director/src/execution/mongo/runs/run.controller.ts
Related issue: #625
[Successfull CI run](https://github.com/bjartur20/sorry-cypress/actions/runs/2888611236)
- Fixed types bug in mongo controller.
- Added typechecking to test job in workflow.
Sorry about the frequent PRs, hoping this is the last one for now 😅
=> Fixed typing error and added typechecks to ci

packages/director/src/execution/__tests__/in-memory.test.ts, packages/director/src/execution/__tests__/mongo.test.ts, packages/director/src/execution/utils.ts
Resolves #634
Also adds testing for GitLab, Github, and BitBucket of the parsing function.
[CI run](https://github.com/bjartur20/sorry-cypress/actions/runs/2939227511)
For bug fixes:
=> Correct parsing of remoteOrigin url

yarn.lock
CVE-2022-36067
https://nvd.nist.gov/vuln/detail/CVE-2022-36067
https://github.com/patriksimek/vm2/issues/467
For bug fixes:
---
=> chore: update vm2 to 3.9.11

cloudformation/sorry-cypress.yml, packages/director/src/execution/mongo/runs/run.controller.ts, packages/director/src/execution/mongo/runs/run.model.ts, packages/director/src/execution/utils.ts
Bug reported here on the original [PR](https://github.com/sorry-cypress/sorry-cypress/pull/641#issuecomment-1251988954)
The cause of the bug was as @vinhoe suggested, the getFailedSpecs function was throwing an error when specs had already in reset.
[Bug ticket](https://github.com/sorry-cypress/sorry-cypress/issues/652#issue-1380911426)
=> fix: director returning 500 using gitlab job retries

packages/dashboard/src/components/ui/player.tsx
When viewing the video, on some screens the side of the video player is quite small. To full screen the video, the user must download the video to watch on their own player, or enable browser video controls on each video they want to view, and then select full screen from that. This new button allows user to full screen the video without any work-around
=> feat: Add Fullscreen button to video player

packages/dashboard/Dockerfile
fixes #690
how I tested:
-  created a new docker using scripts/release-dockerhub.sh
- edited docker-compose.minio.yml to use newly created image
- docker-compose -f docker-compose.minio.yml up
- dashboard just running fine: 
For bug fixes:
---
=> build(dashboard): switch to nginx unprivileged docker

.github/workflows/tests.yml, packages/director/package.json, packages/director/src/lib/hooks/reporters/github.ts, yarn.lock
Requiring all of `octokit` is a bit overkill and installs a lot of packages that are actually not used. Only installing `@octokit/rest` and `@octokit/auth-app` is enough for our use case.
Fixes the linting error mentioned in #695
@agoldis Again sorry for the inconvenience, should have been more thorough
=> Only install necessary octokit packages

packages/dashboard/package.json, packages/dashboard/src/testItem/details/common.tsx, yarn.lock
=> feat: Add screenshot zoom in/out on preview functionality

packages/api/Dockerfile, packages/dashboard/Dockerfile, packages/director/Dockerfile, scripts/release-dockerhub.sh
Running ARM instances especially in AWS is cheaper and more performant. This will allow users to deploy it on AMD or ARM instances
Running locally you can see how this works
```
docker buildx build --file ./packages/api/Dockerfile --platform=linux/arm/v7,linux/amd64 .
[+] Building 1089.0s (41/41) FINISHED                                                                                     
=> [internal] load build definition from Dockerfile                                                                 0.0s
=> => transferring dockerfile: 935B                                                                                 0.0s
=> [internal] load .dockerignore …
```
=> Multi Architecture Docker Images

scripts/release-dockerhub.sh
ARM and AMD builds
Fixes last attempt by fixing typo on `docker buildx create`
```
-> docker buildx create --platform=linux/arm/v7,linux/amd64 --use 
pedantic_jennings
```
=> Fix Multi Arch Build

packages/director/src/screenshots/minio/config.ts, packages/director/src/screenshots/minio/minio.ts, packages/director/src/screenshots/s3/config.ts, packages/director/src/screenshots/s3/s3.ts
Add `UPLOAD_EXPIRY_SECONDS` to control the expiration time for signed URLs
=> feat: add UPLOAD_EXPIRY_SECONDS for signed URL

.github/pull_request_template.md, packages/director/src/config.ts, packages/director/src/screenshots/azure-blob-storage/azure-blob-storage.ts, packages/director/src/screenshots/azure-blob-storage/config.ts, packages/director/src/screenshots/minio/config.ts, packages/director/src/screenshots/s3/config.ts
closes #808
> Describe the use-case in details
=> fix: fix parsing UPLOAD_EXPIRY_SECONDS

packages/director/src/lib/hooks/reporters/slack.ts
- [n/a] I have updated the [documentation](https://github.com/sorry-cypress/gitbook). PR link `<here>`
- [n/a] I have added included automated tests or evidence that it's working
- [n/a] I acknowledge that I have tested that the change is backwards-compatible
- [n/a] Original issue / feature request / discussion: `<here>`
> This is purely a cosmetic improvement for slack reporting to handle newlines better.
=> Update slack.ts for improved newline formatting

packages/director/src/lib/hooks/__tests__/fixtures/slackReportStatusRequest.json, packages/director/src/lib/hooks/__tests__/fixtures/slackReportStatusRequestWithoutCommitData.json, packages/director/src/lib/hooks/reporters/slack.ts
-[n/a] I have updated the [documentation](https://github.com/sorry-cypress/gitbook). PR link <here>
-[x] I have added included automated tests or evidence that it's working
-[n/a] I acknowledge that I have tested that the change is backwards-compatible
-[x] Original issue / feature request / discussion: <here>
This is purely a cosmetic improvement for slack reporting to handle newlines better.
=> Update slack.ts for improved newline formatting 

README.md, packages/dashboard/src/project/projectList.tsx, packages/dashboard/src/project/projectListItem.tsx, yarn.lock
Closes #804 
> Describe the use-case in details
See below issue : [Issue 804](https://github.com/sorry-cypress/sorry-cypress/issues/804)
2 projects with tests executions and 1 project without any execution
I made the choice that when there is no execution, it will show 0 for all tests chips, but if you prefer, we can change that to show no chips. (In term of UI, I prefer with 0) :
=> Issues 804 : Add test chips status to projectList view

packages/dashboard/src/project/projectList.tsx, packages/dashboard/src/project/projectListItem.tsx
Close #841 
- Added specific color instead of the default one (red, pink, etc..) to avoid painful UI for the user.
- Update projectListItem.tsx & projectList.tsx by renaming method.
See directly from the Project page all the failing/flaky/successful project test execution.
=> Issues 841 : Add a background color for each project of /project page

packages/director/src/lib/__tests__/fixtures/issue-881.json, packages/director/src/lib/__tests__/fixtures/issue-XX.json, packages/director/src/lib/__tests__/results.test.ts, packages/director/src/lib/results.ts
When config keys that contain multiple illegal characters an invalid name error is returned. This is because the current sanitise function only replaces the first example of an invalid character rather than every instance. This PR updates the replace function to a regex that globally searches.
=> fix: resolve multiple illegal characters in document keys

packages/api/globalConfig.json, packages/director/src/screenshots/minio/config.ts, packages/director/src/screenshots/minio/minio.ts
In Kubernetes, if Minio is proxied, the generated presigned upload address could look something like
```
http://minio:9000/{bucket}/{key}?{parameters}
```
However that address is not accesssible outside the cluster, outside the cluster it should be for example
```
https://minio.localtest.me/{bucket}/{key}?{parameters}
```
Read URLs translation is already supported using the MINIO_READ_URL_PREFIX environment variable.
Introduce an MINIO_UPLOAD_URL_PREFIX as well. Given `MINIO_UPLOAD_URL_PREFIX=https://minio.localtest.me/{bucket}` it will translate the presigned URL `http://minio:9000/{bucket}/{key}?{parameters}` to the externally accessible `https://minio.localtest.me/{bucket}/{key}?{parameters}`
If the Ingress controller proxy sets the `Host` header to `minio:9000`. Minio presigned url …
=> feat(minio): support for upload to proxied minio

packages/dashboard/src/hooks/useShowFlakySpecs.ts, packages/dashboard/src/run/runDetails/runDetails.tsx, packages/dashboard/src/run/runDetails/runDetailsView.tsx, packages/director/src/lib/hooks/reporters/teams.ts
You can filter by all specs and hide successful specs but you need to check every spec and see the flaky icon to be able to filter by flaky tests. Now you have a button on the top as the hide successful specs button to filter only by the flaky tests. 
The incredible button was added and it's working as expected! :)
=> Add a new button to display only flaky tests

packages/dashboard/src/run/runDetails/runDetails.tsx
After adding the filter by flaky specs button, we realised that it wasn't on the useMemo so you need to press reload in order to load the flaky specs. Now it's fixed.
=> [Fix] Add showFlakySpecs to useMemo 
